---
# file: playbook_group1.yml
- name: Read data files
  ansible.builtin.import_playbook: data.yml

- name: Running play on group1
  hosts: group1 # change this as required
  gather_facts: false # change this as required
  roles:
    - { role: "my-role", tags: "my-tag" }
  vars:
    my_var: "{{ config.my_dict.key }}"
  tags:
    - tag-group1
