---
# file: playbook_group1.yml
- name: Read data files
  ansible.builtin.import_playbook: data.yml

# file: playbook_group2.yml
- name: Running play on group2
  hosts: group2 # change this as required
  gather_facts: false # change this as required
  roles:
    - { role: "my-role", tags: "my-tag" }
  vars:
    my_var: "{{ config.my_dict.key }}"
  tags:
    - tag-group2
